---
# Lakehouse Ingestion (Prod) - CDC pipeline for medallion architecture
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-ingestion-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # After Kafka, Hive, MinIO
spec:
  project: default

  source:
    repoURL: git@github.com:adithyakeshav/lakehouse-ingestion.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: sparkoperator.k8s.io
      kind: SparkApplication
      jsonPointers:
        - /status
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/target/deletionPolicy
